# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_libro_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='parent',
            new_name='padre',
        ),
    ]
