# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20171123_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
