# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20171202_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='padre',
        ),
    ]
