# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0008_remove_libro_padre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together=set([('nombre', 'pertenece')]),
        ),
    ]
